name: Realestate_Assignment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Push to server and deploy
        run: cd /var/www/html && git pull origin master
